on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build step
        run: |
          echo "Building..."
          sleep 5

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy step
        run: |
          echo "Deploying..."
          sleep 5

  test:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Test step
        run: |
          echo "Testing..."
          sleep 5

  deploy-to-prod:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy to Prod step
        run: |
          echo "Deploying to Production..."
          sleep 5
