on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build step
        run: |
          echo "Building..."
          sleep 5

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy step
        run: |
          echo "Deploying..."
          sleep 5

  test:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          npm install
      - name: Set executable permissions for Playwright
        run: |
          chmod +x ./node_modules/.bin/playwright
      - name: Install Playwright browsers
        run: |
          npx playwright install chromium
      - name: Run Playwright tests
        run: |
          npx playwright test

  deploy-to-prod:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy to Prod step
        run: |
          echo "Deploying to Production..."
          sleep 5
